development:
  adapter: sqlite3
  database: db/development.sqlite3
  
test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: openid_fake_server_production
  pool: 5
  username: postgres
  password:
